# Generated by Django 4.2.30 on 2026-04-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('aka', models.CharField(blank=True, default='', max_length=300, verbose_name='Nomes alternativos')),
                ('category', models.CharField(choices=[('weight-loss', 'Perda de Peso'), ('growth-hormone', 'Hormônio do Crescimento'), ('healing', 'Cura e Recuperação'), ('anti-aging', 'Anti-Envelhecimento'), ('skin', 'Pele e Estética'), ('cognitive', 'Cognitivo'), ('immune', 'Sistema Imunológico'), ('hormonal', 'Hormonal'), ('sleep', 'Sono'), ('body-comp', 'Composição Corporal'), ('other', 'Outros')], max_length=30, verbose_name='Categoria')),
                ('category_label', models.CharField(max_length=100, verbose_name='Label da categoria')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('mechanism', models.TextField(verbose_name='Mecanismo de ação')),
                ('administration', models.CharField(max_length=200, verbose_name='Administração')),
                ('half_life', models.CharField(max_length=100, verbose_name='Meia-vida')),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('trial', 'Ensaio Clínico'), ('research', 'Pesquisa')], max_length=20, verbose_name='Status')),
                ('status_label', models.CharField(max_length=100, verbose_name='Label do status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Peptídeo',
                'verbose_name_plural': 'Peptídeos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('goal', models.CharField(choices=[('weight-loss', 'Perda de Peso'), ('growth-hormone', 'Hormônio do Crescimento'), ('healing', 'Cura e Recuperação'), ('anti-aging', 'Anti-Envelhecimento'), ('skin', 'Pele e Estética'), ('cognitive', 'Cognitivo'), ('immune', 'Sistema Imunológico'), ('hormonal', 'Hormonal'), ('sleep', 'Sono'), ('body-comp', 'Composição Corporal'), ('other', 'Outros')], max_length=30, verbose_name='Objetivo')),
                ('goal_label', models.CharField(max_length=100, verbose_name='Label do objetivo')),
                ('level', models.CharField(max_length=50, verbose_name='Nível')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('synergy', models.TextField(verbose_name='Sinergia')),
                ('application', models.TextField(verbose_name='Aplicação')),
                ('duration', models.CharField(max_length=200, verbose_name='Duração')),
                ('warnings', models.TextField(verbose_name='Avisos')),
                ('evidence_level', models.TextField(verbose_name='Nível de evidência')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Combinação',
                'verbose_name_plural': 'Combinações',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StackReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Referência')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.stack')),
            ],
            options={
                'verbose_name': 'Referência do stack',
                'verbose_name_plural': 'Referências do stack',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StackPeptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('role', models.TextField(verbose_name='Papel')),
                ('dose', models.CharField(max_length=300, verbose_name='Dose')),
                ('timing', models.CharField(max_length=200, verbose_name='Timing')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('peptide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_entries', to='core.peptide', verbose_name='Peptídeo vinculado')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_peptides', to='core.stack')),
            ],
            options={
                'verbose_name': 'Peptídeo do stack',
                'verbose_name_plural': 'Peptídeos do stack',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PeptideSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('severity', models.CharField(choices=[('common', 'Comum'), ('occasional', 'Ocasional'), ('rare', 'Raro')], max_length=20, verbose_name='Severidade')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effects', to='core.peptide')),
            ],
            options={
                'verbose_name': 'Efeito colateral',
                'verbose_name_plural': 'Efeitos colaterais',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PeptideReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Referência')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.peptide')),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PeptideDosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=200, verbose_name='Protocolo')),
                ('dose', models.CharField(max_length=200, verbose_name='Dose')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosages', to='core.peptide')),
            ],
            options={
                'verbose_name': 'Dosagem',
                'verbose_name_plural': 'Dosagens',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PeptideBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Benefício')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.peptide')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['order'],
            },
        ),
    ]
