# Generated by Django 5.1.5 on 2026-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='peptide',
            index=models.Index(fields=['category', 'order', 'name'], name='core_peptid_categor_af0a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='peptide',
            index=models.Index(fields=['status'], name='core_peptid_status_86b856_idx'),
        ),
        migrations.AddIndex(
            model_name='stack',
            index=models.Index(fields=['goal', 'order', 'name'], name='core_stack_goal_5a68de_idx'),
        ),
    ]
